# Application
spring.application.name=privacyrisk
server.port=8091

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/privacyrisk
spring.datasource.username=postgres
spring.datasource.password=Prabhala@2004

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Validation
spring.mvc.throw-exception-if-no-handler-found=true

